---
title: "Project Report"
output: html_document
date: "2023-11-17"
---
As this will be your only chance to describe your project in detail, make sure that your report is a standalone document that fully describes your process and results. We also expect you to write high-quality code that is understandable to an outside reader.

**Project Name:** *Operation Lorax - Data Speaks for the Trees!*

**Project Members:** Christine Kuryla, Grace Santos, Sharon Kulali, Stephanie Calluori, Zander De Jesus

## Motivation
Provide an overview of the project goals and motivation.

There is a growing body of evidence demonstrating the beneficial effects of green space exposure on human health ([Yang et al., 2021](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8479545/)). To better inform public health interventions, researchers are diving deeper into the specific aspects of nature, such as urban trees, and their effects on health. Most studies have observed positive effects of urban trees on physical activity and a collection of health outcomes, including respiratory, cardiovascular, and mental health ([Wolf et al., 2020](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7345658/)). However, validation of these results and further exploration of additional health outcomes is needed. In addition, few studies have examined how urban tree exposure may differ across sociodemographic groups ([Wolf et al., 2020](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7345658/)). Here, we focus on New York City using tree data from 2015 (most recent dataset). In this study, we aim to examine the geographic distribution of trees across NYC neighborhoods and potential associations with sociodemographic variables and health outcomes, primarily at the NTA (neighborhood tabulation area as defined by the 2010 census) resolution. Such research will aid in informing public health interventions to promote equitable access to urban trees and improve health. While our analyses are retrospective, our work will lay a foundation that can be used as a comparison point when the next tree census is realeased in 2025, allowing researchers to see how trends may have changed between 2015 and 2025.


## Related work
Anything that inspired you, such as a paper, a web site, or something we discussed in class.

## Initial questions
What questions are you trying to answer? 
How did these questions evolve over the course of the project? 
What new questions did you consider in the course of your analysis?

## Data
Source, scraping method, cleaning, etc.

We found localized Street Tree Survey data collected by the NYC Parks and Recreation Department and volunteer partnerships with community organizations. This dataset provides street addresses for surveyed trees, evaluates species and metrics for tree health, and can be grouped by Borough,  Neighborhood Tabulation Area (NTA) demarcated by 2010 Census, “zip_city” zip code neighborhood level, and as well as latitude and longitude coordinates available for specific point mapping.

The first data resolution of greatest interest to us is the **Neighborhood Tabulation Area (NTA)** level neighborhood. These standardized neighborhood level names are built on the combination of 2010 census tracts, and also nest into larger PUMA regions across New York City. The 1995 dataset Street Tree Survey also has NTA regions brought from the 2010 census for comparison. Many of our auxiliary datasets for comparison on sociodemographic or environmental health data also have 2010 NTA codes.

The second resolution of interest was zipcode / ZCTA, but this data resolution has a few inconsistencies that would need to be cleaned. The tree survey splits zipcode into two columns - “postcode” and associated “zip_city” neighborhood name, but some of these neighborhoods are specific while others are broader borough names of different scales.

To potentially standardize this, we have found:

  - Raw zip code ids (ZCTA) for standardizing NYC and Neighborhood Names Provided by NYCHealth: https://nychealth.github.io/covid-maps/modzcta-geo/about.html
  
  - We could match the neighborhood names associated with these ZCTA codes using joins, and then group tree data by these cleaned ZCTA neighborhood names. 
  
The Street Tree survey appears to be collected citywide every 10 years, and the primary dataset of interest was 2015 data. Previous surveys from 2005 and 1995 are also available and could be used for comparison overtime. We are currently exploring what local sociodemographic datasets are available at neighborhood resolution to think about how tree health and abundance associates with variables like household income, ethnic demographic, surveyed mental wellbeing, etc.

**Main Dataset (NYC Street Tree Survey):**

- 2015 Street Trees: https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh
  - 2005 https://data.cityofnewyork.us/Environment/2005-Street-Tree-Census/29bw-z7pj
  - 1995 https://data.cityofnewyork.us/Environment/1995-Street-Tree-Census/kyad-zm4j	
  
*Primary NTA Level Datasets for Sociodemographics and Environmental Health:*

- NYC Population Breakdown from 2010 Census NTA
  - https://www.nyc.gov/site/planning/planning-level/nyc-population/census-2010.page
  - https://www.nyc.gov/site/planning/data-maps/open-data/census-download-metadata.page
  
- NYC Department of Environmental Health NTA Metrics:
  - https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-stories/geographies/ 
  - Asthma Emergency Visits in NYC
  https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/asthma/?id=2384#display=summary

*Additional Comparative Datasets (Supplemental Depending on the needs of our Research Questions):*

- US Census/ ACS demographic data by County: https://data.census.gov/table/ACSDP1Y2022.DP05?q=demographic&g=050XX00US36005,36047,36061,36081,3608
    - By Zip Code: https://data.census.gov/table/ACSDP5Y2021.DP05?g=040XX00US36$8600000 
    
- Demograpic Youth data by Zip Code: https://data.cityofnewyork.us/City-Government/Demographic-Statistics-By-Zip-Code/kku6-nxdu

- 2015 Community Health profile (has percentages of diff outcomes for each borough): https://www.nyc.gov/site/doh/data/data-publications/profiles-2015-community-health-profiles.page

- Environmental Health Data Portal:
https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/

- Neighborhood name matching / conversion across other resolutions: PUMA, Council District, Census Tracts, Neighborhood Tracking Area 
  - https://guides.newman.baruch.cuny.edu/nyc_data/nbhoods
  - https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-stories/geographies/ 

## Exploratory analysis
Visualizations, summaries, and exploratory statistical analyses. 
Justify the steps you took, and show any major changes to your ideas.

## Additional analysis
If you undertake formal statistical analyses, describe these in detail

## Discussion
What were your findings? 
Are they what you expect? 
What insights into the data can you make?

 