---
title: "About"
---
### About this site

```{r}
# loading the necessary packages

library(tidyverse)
library(plotly)
library(sf)
library(tmap)
library(tmaptools)
library(shinyjs)
```

# Tree Health

```{r}
# importing the data

trees_2015 =
  read_csv("large_tree_data/2015_tree_raw.csv", na = c("", "NA", "Unknown")) |> 
  janitor::clean_names()
```

```{r}
# making a smaller df

trees_df = 
  trees_2015 |> 
  drop_na() |> 
  group_by(postcode, borough, health) |> 
  summarize(
    n_trees = n())

trees_df_nta = 
  trees_2015 |> 
  drop_na() |> 
  group_by(nta_name, postcode, health) |> 
  summarize(
    n_trees = n())
```


```{r}
# reading in the nyc shapefile 

zip_nyc = st_read("small_data/MODZCTA_2010.shp")

str(zip_nyc)
glimpse(zip_nyc)
head(zip_nyc)

tm_shape(zip_nyc) +
  tm_polygons()
```

```{r}
# joining the trees data with sf object

trees_zip =
  merge(zip_nyc, trees_df, 
                        by.x = "MODZCTA",
                        by.y = "postcode") |> 
  janitor::clean_names()

trees_nta = 
  merge(zip_nyc, trees_df_nta, 
                        by.x = "MODZCTA",
                        by.y = "postcode") |> 
  janitor::clean_names()
```

```{r, eval = F}
# getting borough names

trees_zip |> 
  pull(borough) |> 
  unique()

trees_zip |> 
  pull(nta_name) |> 
  unique()
```

```{r}
# map of tree health in all of NYC

trees_zip |> 
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Manhattan")
```

```{r}
# map of tree health in Manhattan

trees_zip |> 
  filter(borough == "Manhattan") |> 
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Manhattan")
```

```{r}
# map of tree health in Brooklyn

trees_zip |> 
  drop_na() |> 
  filter(borough == "Brooklyn") |> 
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Brooklyn")
```

```{r}
# map of tree health in Queens

trees_zip |> 
  drop_na() |> 
  filter(borough == "Queens") |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Queens")
```

```{r}
# map of tree health in Bronx

trees_zip |> 
  drop_na() |> 
  filter(borough == "Bronx") |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Bronx")
```

```{r}
# map of tree health in Staten Island

trees_zip |> 
  drop_na() |> 
  filter(borough == "Staten Island") |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Staten Island")
```

```{r}
# map of tree health in Washington Heights

trees_nta |> 
  drop_na() |> 
  filter(
         nta_name == c("Washington Heights South", "Washington Heights North")) |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Heath by Zip Codes in Washington Heights")
```

```{r}
# interactive map based on tree health in Washington Heights

trees_2015 |>
  drop_na() |> 
  filter(
         nta_name == c("Washington Heights South", "Washington Heights North")) |>
   plot_ly(
       x = ~longitude, y = ~latitude, color = ~health, text = ~spc_common,
       type = "scatter", mode = "markers", alpha = 0.5)
```


