---
title: "From Seed to Sapling:"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: sandstone
    code_folding: hide
---

## Tree Data

```{r, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(readxl)
library(plotly)
library(sf)
library(tmap)
library(tmaptools)
library(shinyjs)
library(ggridges)
library(patchwork)

theme_set(theme_minimal() + theme(legend.position = "right"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
trees_2015 =
  read_csv("large_tree_data/2015_tree_raw.csv", na = c("", "NA", "Unknown")) |> 
  janitor::clean_names() |> 
  mutate(spc_common = str_to_title(spc_common)) |> 
  mutate(health = fct_relevel(health, c("Good", "Fair", "Poor")))
```

## Population

```{r}
pop_race_2010 = readxl::read_excel("small_data/pop_race2010_nta.xlsx", skip = 6, col_names = FALSE, na = "NA") |> 
  rename(
   "borough" = "...1" ,
   "census_FIPS" = "...2",
   "nta" = "...3",
   "nta_name" = "...4",
   "total_population" = "...5",
   "white_nonhis" = "...6",
   "black_nonhis" = "...7",
   "am_ind_alaska_nonhis" = "...8",
   "asian_nonhis" = "...9",
   "hawaii_pac_isl_nonhis" = "...10",
   "other_nonhis" = "...11",
   "two_races" = "...12",
   "hispanic_any_race" = "...13"
  ) |> 
  drop_na()

dem_race = 
  pop_race_2010 |> 
  group_by(borough) |> 
  summarize(white = sum(white_nonhis),
            black = sum(black_nonhis),
            asian = sum(asian_nonhis),
            am_ind_alaska = sum(am_ind_alaska_nonhis),
            hawaii_pac_island = sum(hawaii_pac_isl_nonhis),
            other = sum(other_nonhis),
            hispanic_all_races = sum(hispanic_any_race),
            two_races = sum(two_races)
            ) |> 
  pivot_longer(
    white:two_races,
    names_to = "race",
    values_to = "n"
  ) |> 
   mutate(borough = fct_reorder(borough, n)) 

ggplot(data = dem_race, aes(x = borough, y = n, fill = race)) + geom_bar(stat = 'identity', position = 'dodge')  + 
  labs(
    title = "Population of Borough by Race",
    x = "Borough",
    y = "Total Population"
  )
```

```{r}
pop_race_2010s =  
  pop_race_2010 |> 
  select(- borough, -nta_name)

all_data = left_join(trees_2015, pop_race_2010s, by = "nta")

number_mhtn = 
  all_data |> 
  filter(borough == "Manhattan") |> 
  summarize(n_trees = n_distinct(tree_id))

percentages = 
  all_data |> 
  filter(borough == "Manhattan") |> 
  group_by(nta_name) |> 
  summarize(n_trees = n_distinct(tree_id),
            n_white = (sum(white_nonhis)/sum(total_population)*100),
            n_black = (sum(black_nonhis)/sum(total_population)*100),
            n_asian = (sum(asian_nonhis)/sum(total_population)*100),
            n_pacific_islander = (sum(hawaii_pac_isl_nonhis)/sum(total_population)*100),
            n_amer_ind = (sum(am_ind_alaska_nonhis)/sum(total_population)*100),
            n_other = (sum(other_nonhis)/sum(total_population)*100),
            n_hispanic = (sum(hispanic_any_race)/sum(total_population)*100),
            n_two_races = (sum(two_races)/sum(total_population)*100)
            ) |> 
  mutate(n_trees = as.numeric(n_trees)) |> 
  arrange(desc(n_trees))

percentages |> 
 knitr::kable(digits = 3, caption = "Manhattan Trees and Population Demographics by NTA")
```

```{r}
borough_data = 
  all_data |> 
  group_by(borough) |> 
  summarize(n_trees = n_distinct(tree_id),
            n_white = (sum(white_nonhis)/sum(total_population)*100),
            n_black = (sum(black_nonhis)/sum(total_population)*100),
            n_asian = (sum(asian_nonhis)/sum(total_population)*100),
            n_pacific_islander = (sum(hawaii_pac_isl_nonhis)/sum(total_population)*100),
            n_amer_ind = (sum(am_ind_alaska_nonhis)/sum(total_population)*100),
            n_other = (sum(other_nonhis)/sum(total_population)*100),
            n_hispanic = (sum(hispanic_any_race)/sum(total_population)*100),
            n_two_races = (sum(two_races)/sum(total_population)*100)
            ) |> 
  mutate(n_trees = as.numeric(n_trees)) |> 
  arrange(desc(n_trees))

borough_data |> 
 knitr::kable(digits = 3, caption = "Trees and Population Demographics by Borough")
```

## Poverty

```{r}
acres_raw <- 
  read_excel("small_data/t_pl_p5_nta.xlsx", 
             range = "A9:J203", 
             col_names = c("borough", "county_code", "nta", "nta_name",
                           "total_pop_2000", "total_pop_2010", "pop_change_num",
                           "pop_change_per", "total_acres", "persons_per_acre")
             ) |> 
  janitor::clean_names()

acres_sub <- acres_raw |> 
  select(nta_name, total_acres)

trees_per_nta <- trees_2015 |> 
  select(nta_name, nta, borough, status) |> 
  filter(status == "Alive") |> 
  count(nta_name, borough) |> 
  rename(num_trees = n)

trees_and_acres <- left_join(trees_per_nta, acres_sub, by = "nta_name")

num_missing_nta <- sum(is.na(trees_and_acres$total_acres))

trees_per_acre_df <- trees_and_acres |> 
  filter(!is.na(total_acres)) |> 
  mutate(trees_per_acre = num_trees/total_acres) |> 
  arrange(desc(trees_per_acre))

poverty_raw <-
  read_csv("large_tree_data/NYC EH Data Portal - Neighborhood poverty.csv") |> 
  janitor::clean_names()

poverty_clean <- poverty_raw |> 
  rename(nta_name = geography, poverty_percent = percent) |> 
  filter(geo_type == "NTA2010" & time == "2013-17") |> 
  select(nta_name, poverty_percent)

trees_and_poverty <- left_join(trees_per_acre_df, poverty_clean, by = "nta_name")

trees_and_poverty |> 
  plot_ly(data = _, x = ~poverty_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, 
                        "<br>%below poverty line: ", poverty_percent, 
                        "<br>trees per acre: ", trees_per_acre)) |> 
    layout(title = "Percent below the poverty line and trees per acre in NYC",
           xaxis = list(title = 'Percentage of people whose income <br> is below the poverty line'),
           yaxis = list(title = 'Number of trees per acre'),
           legend = list(title=list(text='Neighborhood')))

cor(pull(trees_and_poverty, trees_per_acre), pull(trees_and_poverty, poverty_percent))
```

```{r}
trees_and_poverty |> 
  filter(borough == "Manhattan") |> 
  plot_ly(data = _, x = ~poverty_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, 
                        "<br>%below poverty line: ", poverty_percent, 
                        "<br>trees per acre: ", trees_per_acre)) |> 
    layout(title = "Percent below the poverty line and trees per acre in Manhattan",
           xaxis = list(title = 'Percentage of people whose income <br> is below the poverty line'),
           yaxis = list(title = 'Number of trees per acre'),
           legend = list(title=list(text='Neighborhood')))

manhattan_trees_and_poverty <- trees_and_poverty |> 
  filter(borough == "Manhattan")

cor(pull(manhattan_trees_and_poverty, trees_per_acre), pull(manhattan_trees_and_poverty, poverty_percent))
```

```{r}
trees_and_poverty |> 
  filter(borough == "Brooklyn") |> 
  plot_ly(data = _, x = ~poverty_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, 
                        "<br>%below poverty line: ", poverty_percent, 
                        "<br>trees per acre: ", trees_per_acre)) |> 
    layout(title = "Percent below the poverty line and trees per acre in Brooklyn",
           xaxis = list(title = 'Percentage of people whose income <br> is below the poverty line'),
           yaxis = list(title = 'Number of trees per acre'),
           legend = list(title=list(text='Neighborhood')))

brooklyn_trees_and_poverty <- trees_and_poverty |> 
  filter(borough == "Brooklyn")

cor(pull(brooklyn_trees_and_poverty, trees_per_acre), pull(brooklyn_trees_and_poverty, poverty_percent))
```

```{r}
trees_and_poverty |> 
  filter(borough == "Bronx") |> 
  plot_ly(data = _, x = ~poverty_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, 
                        "<br>%below poverty line: ", poverty_percent, 
                        "<br>trees per acre: ", trees_per_acre)) |> 
    layout(title = "Percent below the poverty line and trees per acre in Bronx",
           xaxis = list(title = 'Percentage of people whose income <br> is below the poverty line'),
           yaxis = list(title = 'Number of trees per acre'),
           legend = list(title=list(text='Neighborhood')))

bronx_trees_and_poverty <- trees_and_poverty |> 
  filter(borough == "Bronx")

cor(pull(bronx_trees_and_poverty, trees_per_acre), pull(bronx_trees_and_poverty, poverty_percent))
```

```{r}
trees_and_poverty |> 
  filter(borough == "Staten Island") |> 
  plot_ly(data = _, x = ~poverty_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, 
                        "<br>%below poverty line: ", poverty_percent, 
                        "<br>trees per acre: ", trees_per_acre)) |> 
    layout(title = "Percent below the poverty line and trees per acre in Staten Island",
           xaxis = list(title = 'Percentage of people whose income <br> is below the poverty line'),
           yaxis = list(title = 'Number of trees per acre'),
           legend = list(title=list(text='Neighborhood')))

staten_island_trees_and_poverty <- trees_and_poverty |> 
  filter(borough == "Staten Island")

cor(pull(staten_island_trees_and_poverty, trees_per_acre), pull(staten_island_trees_and_poverty, poverty_percent))
```

```{r}
trees_and_poverty |> 
  filter(borough == "Queens") |> 
  plot_ly(data = _, x = ~poverty_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, 
                        "<br>%below poverty line: ", poverty_percent, 
                        "<br>trees per acre: ", trees_per_acre)) |> 
    layout(title = "Percent below the poverty line and trees per acre in Queens",
           xaxis = list(title = 'Percentage of people whose income <br> is below the poverty line'),
           yaxis = list(title = 'Number of trees per acre'),
           legend = list(title=list(text='Neighborhood')))

queens_trees_and_poverty <- trees_and_poverty |> 
  filter(borough == "Queens")

cor(pull(queens_trees_and_poverty, trees_per_acre), pull(queens_trees_and_poverty, poverty_percent))
```

## Education

```{r}
education_raw <-
  read_csv("large_tree_data/NYC EH Data Portal - Graduated high school.csv") |> 
  janitor::clean_names()


education_clean <- education_raw |> 
  rename(nta_name = geography, graduated_hs_percent = percent) |> 
  filter(geo_type == "NTA2010" & time == "2013-17") |> 
  select(nta_name, graduated_hs_percent)

trees_and_education <- left_join(trees_per_acre_df, education_clean, by = "nta_name")

trees_and_education |> 
  plot_ly(data = _, x = ~graduated_hs_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, "<br>% graduated HS: ", 
                        graduated_hs_percent, "<br>trees per acre: ", trees_per_acre)) |> 
  layout(title = "Percent graduated high school and trees per acre in NYC", 
         xaxis = list(title = 'Percent graduated <br> high school (includes equivalency)'), 
         yaxis = list(title = 'Number of trees per acre'), 
         legend = list(title=list(text='Neighborhood')))

cor(pull(trees_and_education, trees_per_acre), pull(trees_and_education, graduated_hs_percent))
```

```{r}
trees_and_education |> 
  filter(borough == "Manhattan") |> 
  plot_ly(data = _, x = ~graduated_hs_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, "<br>% graduated HS: ", 
                        graduated_hs_percent, "<br>trees per acre: ", trees_per_acre)) |> 
  layout(title = "Percent graduated high school and trees per acre in Manhattan", 
         xaxis = list(title = 'Percent graduated <br> high school (includes equivalency)'), 
         yaxis = list(title = 'Number of trees per acre'), 
         legend = list(title=list(text='Neighborhood')))

manhattan_trees_and_education <- trees_and_education |> 
  filter(borough == "Manhattan")

cor(pull(manhattan_trees_and_education, trees_per_acre), pull(manhattan_trees_and_education, graduated_hs_percent))
```

```{r}
trees_and_education |> 
  filter(borough == "Brooklyn") |> 
  plot_ly(data = _, x = ~graduated_hs_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, "<br>% graduated HS: ", 
                        graduated_hs_percent, "<br>trees per acre: ", trees_per_acre)) |> 
  layout(title = "Percent graduated high school and trees per acre in Brooklyn", 
         xaxis = list(title = 'Percent graduated <br> high school (includes equivalency)'), 
         yaxis = list(title = 'Number of trees per acre'), 
         legend = list(title=list(text='Neighborhood')))

brooklyn_trees_and_education <- trees_and_education |> 
  filter(borough == "Brooklyn")

cor(pull(brooklyn_trees_and_education, trees_per_acre), pull(brooklyn_trees_and_education, graduated_hs_percent))
```

```{r}
trees_and_education |> 
  filter(borough == "Bronx") |> 
  plot_ly(data = _, x = ~graduated_hs_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, "<br>% graduated HS: ", 
                        graduated_hs_percent, "<br>trees per acre: ", trees_per_acre)) |> 
  layout(title = "Percent graduated high school and trees per acre in Bronx", 
         xaxis = list(title = 'Percent graduated <br> high school (includes equivalency)'), 
         yaxis = list(title = 'Number of trees per acre'), 
         legend = list(title=list(text='Neighborhood')))

bronx_trees_and_education <- trees_and_education |> 
  filter(borough == "Bronx")

cor(pull(bronx_trees_and_education, trees_per_acre), pull(bronx_trees_and_education, graduated_hs_percent))
```

```{r}
trees_and_education |> 
  filter(borough == "Staten Island") |> 
  plot_ly(data = _, x = ~graduated_hs_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, "<br>% graduated HS: ", 
                        graduated_hs_percent, "<br>trees per acre: ", trees_per_acre)) |> 
  layout(title = "Percent graduated high school and trees per acre in Staten Island", 
         xaxis = list(title = 'Percent graduated <br> high school (includes equivalency)'), 
         yaxis = list(title = 'Number of trees per acre'), 
         legend = list(title=list(text='Neighborhood')))

staten_island_trees_and_education <- trees_and_education |> 
  filter(borough == "Staten Island")

cor(pull(staten_island_trees_and_education, trees_per_acre), pull(staten_island_trees_and_education, graduated_hs_percent))
```


```{r}
trees_and_education |> 
  filter(borough == "Queens") |> 
  plot_ly(data = _, x = ~graduated_hs_percent, y = ~trees_per_acre, 
          color = ~nta_name,
          colors = "viridis", 
          type = "scatter",
          mode = "markers",
          text = ~paste("neighborhood: ", nta_name, "<br>borough: ", borough, "<br>% graduated HS: ", 
                        graduated_hs_percent, "<br>trees per acre: ", trees_per_acre)) |> 
  layout(title = "Percent graduated high school and trees per acre in Queens", 
         xaxis = list(title = 'Percent graduated <br> high school (includes equivalency)'), 
         yaxis = list(title = 'Number of trees per acre'), 
         legend = list(title=list(text='Neighborhood')))

queens_trees_and_education <- trees_and_education |> 
  filter(borough == "Queens")

cor(pull(queens_trees_and_education, trees_per_acre), pull(queens_trees_and_education, graduated_hs_percent))
```

