---
title: "May the Forest be With Us: Distribution of NYC Trees"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: sandstone
    code_folding: hide
---

## Tree Data

```{r, warning = F, message = F, echo = F}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(readxl)
library(plotly)
library(sf)
library(tmap)
library(tmaptools)
library(shinyjs)
library(ggridges)
library(patchwork)

theme_set(theme_minimal() + theme(legend.position = "right"))

options(
  ggplot2.continuous.colour = "virdis",
  ggplot2.continuous.fill = "virdis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
trees_2015 =
  read_csv("large_tree_data/2015_tree_raw.csv", na = c("", "NA", "Unknown")) |> 
  janitor::clean_names() |> 
  mutate(spc_common = str_to_title(spc_common)) |> 
  mutate(health = fct_relevel(health, c("Good", "Fair", "Poor")))
```

## Tree Count

```{r}
pop_race_2010 = readxl::read_excel("small_data/pop_race2010_nta.xlsx", skip = 6, col_names = FALSE, na = "NA") |> 
  rename(
   "borough" = "...1" ,
   "census_FIPS" = "...2",
   "nta" = "...3",
   "nta_name" = "...4",
   "total_population" = "...5",
   "white_nonhis" = "...6",
   "black_nonhis" = "...7",
   "am_ind_alaska_nonhis" = "...8",
   "asian_nonhis" = "...9",
   "hawaii_pac_isl_nonhis" = "...10",
   "other_nonhis" = "...11",
   "two_races" = "...12",
   "hispanic_any_race" = "...13"
  ) |> 
  drop_na() |> 
  select(- borough, -nta_name)

all_data = left_join(trees_2015, pop_race_2010, by = "nta")

number_tree = 
  all_data |> 
  group_by(borough) |> 
  summarize(n_trees = n_distinct(tree_id)) |> 
  mutate(borough = fct_reorder(borough, n_trees))

ggplot(data = number_tree, aes(x = borough, y = n_trees, fill = borough)) + geom_bar(stat = 'identity') + geom_text(aes(label = n_trees), size = 3, vjust = -1) + 
  labs(
    title = "Number of Trees in each Borough",
    x = "Borough",
    y = "Total Number of Trees"
  )
```

```{r}
queens_rare_trees = 
  all_data |> 
  filter(borough == "Queens") |>
  count(spc_common) |> 
  filter(n < 500) |> 
  mutate(spc_common = fct_reorder(spc_common, n))

ggplot(data = queens_rare_trees, aes(x = spc_common, y = n, fill = spc_common)) + geom_bar(stat = 'identity') + theme(legend.position = "none", axis.text.x = element_text(angle = 65, hjust=1)) + 
  labs(
    title = "Species of Trees in Queens",
    x = "Species (common name)",
    y = "Total Number of Trees"
  )
```

```{r}
mhtn_number_tree = 
  all_data |> 
  filter(borough == "Manhattan") |> 
  group_by(nta_name) |> 
  summarize(n_trees = n_distinct(tree_id),
            n_population = (sum(total_population)/100000)) |> 
  pivot_longer(
    n_trees:n_population,
    names_to = "type",
    names_prefix = "n_",
    values_to = "total"
  ) |> 
   mutate(nta_name = fct_reorder(nta_name, total))
  

ggplot(mhtn_number_tree, aes(x = nta_name, y = total, fill = type)) + geom_bar(stat = 'identity', position = 'dodge')+ theme(axis.text.x = element_text(angle = 65, hjust=1)) + 
  labs(
    title = "Number of Trees in Manhattan by NTA",
    x = "Neighborhood Tabulation Area",
    y = "Total Number of Trees"
  )
```

```{r}
acres_raw <- 
  read_excel("small_data/t_pl_p5_nta.xlsx", 
             range = "A9:J203", 
             col_names = c("borough", "county_code", "nta", "nta_name",
                           "total_pop_2000", "total_pop_2010", "pop_change_num",
                           "pop_change_per", "total_acres", "persons_per_acre")
             ) |> 
  janitor::clean_names()

acres_sub <- acres_raw |> 
  select(nta_name, total_acres)

trees_per_nta <- trees_2015 |> 
  select(nta_name, nta, borough, status) |> 
  filter(status == "Alive") |> 
  count(nta_name, borough) |> 
  rename(num_trees = n)

trees_and_acres <- left_join(trees_per_nta, acres_sub, by = "nta_name")

num_missing_nta <- sum(is.na(trees_and_acres$total_acres))

trees_per_acre_df <- trees_and_acres |> 
  filter(!is.na(total_acres)) |> 
  mutate(trees_per_acre = num_trees/total_acres) |> 
  arrange(desc(trees_per_acre))

trees_per_acre_nta_table <- trees_per_acre_df |> 
  filter(min_rank(desc(trees_per_acre)) < 11) |> 
  knitr::kable(digits = 2, caption = "Top 10 NYC Neighborhoods with the Highest Number of Trees per Acre")

trees_per_acre_nta_table

trees_total_nta_table <- trees_per_acre_df |> 
  filter(min_rank(desc(num_trees)) < 11) |> 
  knitr::kable(digits = 2, caption = "Top 10 NYC Neighborhoods with the Highest Total Number of Trees")

trees_total_nta_table
```

```{r}
nyc_nta = st_read("small_data/geo_export_e924b274-8b6e-427d-87c0-92bfde8ce30a.shp")

nta_dbh_summarized = trees_2015 |> 
  drop_na(tree_dbh) |> 
  group_by(nta) |> 
  summarize(
    trees_per_nta = n(),
    avg_dbh = mean(tree_dbh))


nta_dbh_spatial = merge(nyc_nta, nta_dbh_summarized, 
                        by.x = "ntacode",
                        by.y = "nta")

tm_shape(nta_dbh_spatial) +
  tm_polygons(col = "trees_per_nta",
              style = "quantile",
              n = 5,
              palette = "Greens",
              border.col = "black",
              title = "Number of Trees per NTA") +
  tm_layout(main.title = "Total Tree Count Across NYC Neighborhoods", main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.position = c("left","center"),
            legend.text.size = 0.52)
```

## Tree Species

```{r}
top_trees_nyc <- trees_2015 %>% 
  drop_na(spc_common) %>%   
  group_by(spc_common) %>%
  count(spc_common) %>% 
  arrange(desc(n)) %>% 
  head(n = 10) %>% 
  pull(spc_common)

 trees_2015 %>% 
    drop_na(spc_common, borough) %>% 
    group_by(spc_common, borough) %>%
    count(spc_common) %>% 
    filter(spc_common %in% top_trees_nyc) %>% 
    pivot_wider(names_from = borough, values_from = n) %>% 
    mutate(`All Boroughs Average` = mean(Bronx:`Staten Island`)) %>% 
    select(spc_common, `All Boroughs Average`, everything()) %>% 
    pivot_longer(cols = `All Boroughs Average`:`Staten Island`) %>% 
    ggplot(aes(x = reorder(spc_common, value), y = value, fill = spc_common)) +
    geom_bar(stat = "identity") +
    facet_wrap(~ name) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "Tree Species", 
         y = "Number of Trees", 
         fill = "Tree Species",
         title = "Top Ten NYC Trees Overall and in Each NYC Borough")
```

```{r}
trees_2015 %>%
  drop_na() %>%
  group_by(borough, spc_common) %>%
  count() %>%
  arrange(borough, desc(n)) %>%
  group_by(borough) %>%
  slice_max(n = 10, order_by = n) %>% 
  select(-n) %>% 
  group_by(borough) %>%
  mutate(row_num = row_number()) %>%
  pivot_wider(names_from = borough, values_from = spc_common) %>% 
  unnest(cols = c(Bronx, Brooklyn, Manhattan, Queens, `Staten Island`)) %>% 
  select(row_num, everything()) %>% 
  knitr::kable(caption = "Top 10 Tree Species in Each Borough")
```

```{r}
queens_prev_trees = 
  all_data |> 
  drop_na() |> 
  filter(borough == "Queens") |>
  count(spc_common) |> 
  filter(n > 500) |> 
  mutate(spc_common = fct_reorder(spc_common, n))

ggplot(data = queens_prev_trees, aes(x = spc_common, y = n, fill = spc_common)) + geom_bar(stat = 'identity') + theme(legend.position = "none", axis.text.x = element_text(angle = 65, hjust=1)) + 
  labs(
    title = "Species of Trees in Queens",
    x = "Species (common name)",
    y = "Total Number of Trees"
  )
```

## Tree DBH

```{r}
trees_dbh = trees_2015 |> 
  drop_na(tree_dbh) |> 
  group_by(borough, nta_name) |> 
  summarize(
    n_trees = n(),
    avg_dbh = mean(tree_dbh)) |> 
  arrange(desc(avg_dbh))

trees_dbh |> 
  ungroup() |> 
  filter(n_trees > 100) |> 
  filter(min_rank(desc(avg_dbh)) < 11) |> 
  knitr::kable(digits = 2, caption= "Top 10 Neighborhoods with the Highest Average DBH (inches) Across Local Street Trees")
```

```{r}
borough_dbh = trees_2015 |> 
  drop_na(tree_dbh) |> 
  group_by(borough) |> 
  mutate(borough_dbh = mean(tree_dbh))

borough_dbh |> 
  filter(tree_dbh < 101) |> 
  plot_ly(y = ~tree_dbh, color = ~borough, type = "box", colors = "viridis") |> 
  layout(title = "Distribution of DBH in Each Borough",
         xaxis = list(title = 'Borough'),
         yaxis = list(title = 'Measured DBH (inches)'),
        showlegend = FALSE)
```

```{r}
borough_dbh |> 
  filter(tree_dbh < 50) |> 
  ggplot(aes(x = tree_dbh, fill = borough)) + 
  geom_density() + facet_grid(borough ~ .) +
  scale_x_continuous(breaks = scales::pretty_breaks(12)) +
  labs(
    title = "Density Plot of All Measured Tree Diameters Below 50 inches",
    x = "Measured DBH (Inches)",
    y = "Density"
  )
```

```{r}
tm_shape(nta_dbh_spatial) +
  tm_polygons(col = "avg_dbh",
              style = "quantile",
              n = 5,
              palette = "YlGn",
              border.col = "black",
              title = "Mean Tree DBH (Inches)") +
  tm_layout(main.title = "Average Tree DBH Across NYC Neighborhoods",
            main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.position = c("left","center"),
            legend.text.size = 0.52)
```

## Tree Health Status

```{r}
zip_nyc = st_read("small_data/MODZCTA_2010.shp")

trees_df = 
  trees_2015 |> 
  drop_na() |> 
  group_by(postcode, borough, health) |> 
  summarize(
    n_trees = n())

trees_zip =
  merge(zip_nyc, trees_df, 
                        by.x = "MODZCTA",
                        by.y = "postcode") |> 
  janitor::clean_names()

trees_zip |> 
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes in NYC",
            main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.position = c("left","center"),
            legend.text.size = 0.52)
```

```{r}
trees_zip |> 
  filter(borough == "Manhattan") |> 
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes
            in Manhattan",
            main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.text.size = 0.52)
```

```{r}
trees_zip |> 
  drop_na() |> 
  filter(borough == "Brooklyn") |> 
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes in Brooklyn",
             main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.text.size = 0.52)
```

```{r}
trees_zip |> 
  drop_na() |> 
  filter(borough == "Queens") |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes in Queens",
             main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.text.size = 0.52)
```

```{r}
trees_zip |> 
  drop_na() |> 
  filter(borough == "Bronx") |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes in Bronx",
             main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.text.size = 0.52)
```

```{r}
trees_zip |> 
  drop_na() |> 
  filter(borough == "Staten Island") |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes in Staten Island",
             main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.text.size = 0.52)
```

```{r}
trees_df_nta = 
  trees_2015 |> 
  drop_na() |> 
  group_by(nta_name, postcode, health) |> 
  summarize(
    n_trees = n())

trees_nta = 
  merge(zip_nyc, trees_df_nta, 
                        by.x = "MODZCTA",
                        by.y = "postcode") |> 
  janitor::clean_names()

trees_nta |> 
  drop_na() |> 
  filter(
         nta_name %in% c("Washington Heights South", "Washington Heights North")) |>
  tm_shape() +   
  tm_polygons(col = "health",
              style = "equal",
              n = 3,
              palette = "viridis",
              border.col = "black",
              title = "Tree Health Status")+
  tm_layout(main.title = "Tree Heath by Zip Codes 
            in Washington Heights",
             main.title.size = 1,
            frame = FALSE) +
  tm_legend(legend.text.size = 0.52)
```

```{r}
trees_2015 |>
  drop_na() |> 
  filter(
         nta_name %in% c("Washington Heights South", "Washington Heights North")) |>
   plot_ly(color = ~health, colors = "viridis") |> 
  add_trace(
    type = "scattermapbox",
    mode = "markers",
    lon = ~longitude,
    lat = ~latitude,
    marker = list(size = 5),
    text = ~spc_common,
    below = "markers"
  ) |> 
  layout(
    title = "Tree Health in Washington Heights",
    mapbox = list(
      style = "carto-positron",  
      center = list(lon = -73.94, lat = 40.84), 
      zoom = 12
    ),
    showlegend = T
  )
```

## Other

```{r}
trees_2015 %>%
  filter(brch_shoe == "Yes") %>%
  mutate(borough = fct_infreq(borough)) %>%
  ggplot(aes(x = borough, fill = borough)) +
  geom_bar() +
  labs(title = "Number of Trees with Shoes on Them", x = "Borough", y = "Count")
```